// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://fjoogathnnpzljisdcrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqb29nYXRobm5wemxqaXNkY3JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4Mzk5NjYsImV4cCI6MjA3MzQxNTk2Nn0.vAfSH11JJ4JwKN0kqv7BKbB-6pbenaAKw88lh9JOHKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);